#ifndef CONFIG_H
#define CONFIG_H

#define ENABLE_DEBUG 0
#define ENABLE_IOT 1

#define WIFI_SSID "YOUR-WIFI-SSID"
#define WIFI_PASSWORD "YOUR-WIFI-PASSWORD"

#define PIN_BUZZER 25
#define PIN_SDA 21
#define PIN_SCL 22
#define I2C_SPEED 400000L

#define SAMPLING_INTERVAL_MS 50

#define REFRESH_INTERVAL_MS 100
#define SCREEN_BLINK_INTERVAL_MS 90
#define UPLOAD_FADE_INTERVAL_MS 490

#define PROCESSING_INTERVAL_MS 1000
#define UPLOAD_INTERVAL_MS 15000

#define DEVICE_INIT_WAIT 2000

#define HR_BUFFER_SIZE 20
#define HR_SUM_WINDOW_SIZE 6

#define EPSILON 0.001

#endif
